stages:
  train_data_dir:
    cmd: python3.6 /data/exp/kostya/ukroASR/gen_data_dir.py /data/exp/kostya/ukroASR/data/raw_data/train.csv
      /data/exp/kostya/ukroASR/data/train
    deps:
    - data/raw_data/train.csv
    - gen_data_dir.py
    outs:
    - data/train/segments
    - data/train/spk2utt
    - data/train/text
    - data/train/utt2spk
    - data/train/wav.scp
  dev_data_dir:
    cmd: python3.6 /data/exp/kostya/ukroASR/gen_data_dir.py /data/exp/kostya/ukroASR/data/raw_data/dev.csv
      /data/exp/kostya/ukroASR/data/dev
    deps:
    - data/raw_data/dev.csv
    - gen_data_dir.py
    outs:
    - data/dev/segments
    - data/dev/spk2utt
    - data/dev/text
    - data/dev/utt2spk
    - data/dev/wav.scp
  local_dict:
    cmd: /data/exp/kostya/ukroASR/prepare_dict.sh /data/exp/kostya/ukroASR/data/local/dict
      /data/exp/kostya/ukroASR/data/train/text /data/exp/kostya/ukroASR/artifacts/text_plane
    deps:
    - artifacts/lexicon.txt
    - artifacts/text_plane
    - data/train/text
    outs:
    - data/local/dict/lexicon.txt
    - data/local/dict/vocab
  lang_dir:
    cmd: cd $KALDI_ROOT/egs/wsj/s5; . ./path.sh; . ./cmd.sh; utils/prepare_lang.sh
      --position-dependent-phones false /data/exp/kostya/ukroASR/data/local/dict '<UNK>'
      /data/exp/kostya/ukroASR/data/local/lang /data/exp/kostya/ukroASR/data/lang
    deps:
    - data/local/dict/extra_questions.txt
    - data/local/dict/lexicon.txt
    - data/local/dict/nonsilence_phones.txt
    - data/local/dict/optional_silence.txt
    - data/local/dict/silence_phones.txt
    outs:
    - data/lang/L.fst
    - data/lang/L_disambig.fst
    - data/lang/oov.int
    - data/lang/oov.txt
    - data/lang/phones
    - data/lang/phones.txt
    - data/lang/topo
    - data/lang/words.txt
    - data/local/dict/lexiconp.txt:
        cache: false
  lm_ukr:
    cmd: cut -d' ' -f2- /data/exp/kostya/ukroASR/data/train/text /data/exp/kostya/ukroASR/artifacts/text_plane
      | ngram-count -text - -order 3 -gt1min 1 -gt2min 1 -lm - | gzip -c > /data/exp/kostya/ukroASR/data/lm_ukr.gz
    deps:
    - artifacts/text_plane
    - data/train/text
    outs:
    - data/lm_ukr.gz
  lm_metrics:
    cmd: "echo {\\'LM perplexity\\': 2407.197} > /data/exp/kostya/ukroASR/exp/metrics/lm.json"
    deps:
    - data/dev/text
    - data/lm_ukr.gz
    metrics:
    - exp/metrics/lm.json
  lang_fst:
    cmd: cd $KALDI_ROOT/egs/wsj/s5; . ./path.sh; . ./cmd.sh; utils/format_lm.sh /data/exp/kostya/ukroASR/data/lang
      /data/exp/kostya/ukroASR/data/lm_ukr.gz /data/exp/kostya/ukroASR/data/local/dict/lexicon.txt
      /data/exp/kostya/ukroASR/data/lang
    deps:
    - data/lang/words.txt
    - data/lm_ukr.gz
    - data/local/dict/lexicon.txt
    outs:
    - data/lang/G.fst
